name: Build distribution

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          lfs: true
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: ./build.sh ci
      - uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: build/dist/*
  publishArtifacts:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Fetch git tags.
        run: git fetch --prune --unshallow --tags

      - name: Get version as Github variable.
        run: 'echo "VERSION_STR=ci_draft-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV'

      - uses: actions/download-artifact@v4
        with:
          name: dist-packages
          path: artifacts

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.VERSION_STR }}
          message: CI release ${{ env.VERSION_STR }}
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.VERSION_STR }}
          tag_name: ${{ env.VERSION_STR }}
          body: |
            CI Build ${{ env.VERSION_STR }}
            This is an development draft release. Expect that anything may change without notice, and that things may make zero sense.
          prerelease: true
          files: artifacts/**
          fail_on_unmatched_files: true
          generate_release_notes: true
